### ISSUE TITLE
Re-exported bundles do not show in exported packages

### ISSUE THREAD

**Issue by sgandon** [iloveeclipse/plugindependencies#2]
when inspecting exported packages of a bundle the re-exported required bundles (Require-Bundle: javax.xml.rpc,org.apache.axis**;visibility:=reexport**) should also contribute to exported packages as they really do in an OSGI runtime.

**Comment by iloveeclipse** [comment]
Should be done via 7ef3c5cf81563dcb243fac7e24a683adcb7e47ed
