### ISSUE TITLE
How to actually USE this tool?

### ISSUE THREAD

**Issue by davidmichaelkarr** [iloveeclipse/plugindependencies#3]
I've installed the Eclipse plugin, but I see no information on how to USE this thing.  I see no preferences, no views, no interface to use this.  This project also talks about a command-line interface, but I see no information about that anywhere.

**Comment by iloveeclipse** [comment]
This plugin is written for myself and so I don't need this kind of documentation, but you are absolutely right, I forgot to add this info. I've updated the readme.

**Comment by davidmichaelkarr** [comment]
If this plugin is "written for myself", then why did you create an Eclipse Marketplace entry?

**Comment by iloveeclipse** [comment]
Because I write all my plugins for myself, and sometimes they are useful for others too :-)
It's open source & free as a free beer, I don't charge money from you for the plugin. 

You are welcome to improve the docu/code whatever you like :-)
