### ISSUE TITLE
How to use the Plugin Explorer view?

### ISSUE THREAD

**Issue by davidmichaelkarr** [iloveeclipse/plugindependencies#4]
Ok, now I know from the README that this creates the "Plugin Explorer" view. What do I do with this view? I see the "Load Target Definition" button. What is a "target"?  The little information I can find about the plugikn says "Plugin provides both command line and Eclipse UI for static package, plugin and feature dependencies analysis (the dependencies are read from MANIFEST.MF and feature.xml files)." I tried entering "features.xml" in the target search field, thinking that it would find the "features.xml" files in my project, but nothing came up in the list.

I have no idea what to do here.

**Comment by iloveeclipse** [comment]
I've updated docu again, feedback is welcome.
