### ISSUE TITLE
Installing Plugin Dependencies Explorer will uninstall JustJ JRE

### ISSUE THREAD

**Issue by bjmi** [iloveeclipse/plugindependencies#6]
I'd like to install _Plugin Dependencies Explorer_ via update site. Unfortunately this will uninstall the desired JustJ JRE.
Is it possible to fix this or does a work-around exist?
Thanks in advance
<img width="749" alt="image" src="https://user-images.githubusercontent.com/2063480/154046945-c0feaf0a-e291-4b8b-9958-14be7cd5f349.png">

**Comment by iloveeclipse** [comment]
Yaeh, I know, that was my workaround for
https://bugs.eclipse.org/bugs/show_bug.cgi?id=569871

There is a possibility it is not needed anymore, I can check that later.

**Comment by iloveeclipse** [comment]
@bjmi :  should be fixed, please verify (I've pushed new version to the update site).

**Comment by bjmi** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/2063480/158770543-a3b0af90-0216-4412-ab65-1d8c251c0160.png">
Looks good to me now.
Thank you.
