### ISSUE TITLE
NPE when logging broken entry

### ISSUE THREAD

**Issue by HannesWell** [iloveeclipse/plugindependencies#7]
When running an analysis of a mixed Modular-Target (mostly Eclipse Platform projects) I get the following Exception:
```
java.lang.NullPointerException
	at org.eclipselabs.plugindependencies.core.OSGIElement.logBrokenEntry(OSGIElement.java:137)
	at org.eclipselabs.plugindependencies.core.DependencyResolver.searchHost(DependencyResolver.java:214)
	at org.eclipselabs.plugindependencies.core.DependencyResolver.resolvePluginDependency(DependencyResolver.java:65)
	at org.eclipselabs.plugindependencies.core.PlatformState.resolveDependencies(PlatformState.java:531)
	at org.eclipselabs.plugindependencies.core.PlatformState.computeAllDependenciesRecursive(PlatformState.java:337)
	at org.eclipselabs.plugindependencies.ui.view.ViewContentProvider$LoadTarget.run(ViewContentProvider.java:262)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by iloveeclipse** [comment]
@HannesWell : should be fixed, please verify (I've pushed new version to the update site).

**Comment by HannesWell** [comment]
> @HannesWell : should be fixed, please verify (I've pushed new version to the update site).

Thank you, works well now!

This tool is very handy! Have you already considered to contribute it to PDE?
There are already multiple views in PDE, namely the `Features`, `Plug-ins`, `Plug-in Registry` and `Target Platform State`, that offer partially similar features to each other and to this Plug-in but do not cover everything this Plug-in can.

If possible I would be in favor to merge these views into one or two and enhance them with the capabilities of this Plug-in.

**Comment by iloveeclipse** [comment]
Few things. 
1) I fear the tool is not 100% correct / complies to the specs. It is written mostly to achieve the goal to quickly find potential platform issues and / or investigate what is coming from where and via which dependency chain. It is more of practical / empirical kind, less of "that is the truth about your p2 install".
2) Core part is used as commmand line app that serves very specific needs we have at my day job and has zero dependencies. It is used via ant before compilation to generate dependency graphs, classpath entries for ant and check for possible errors. There is no need in PDE for that, especially if we build "modern" apps with tycho.

Therefore I'm fine with the current situation and do not plan contribute it to PDE.

**Comment by HannesWell** [comment]
Understand that. 
Nevertheless I still think the mentioned other views should be merged/streamlined and in this process could also be enhanced.
Do you mind if I get inspired by this plug-in? Although I likely wont have time for this soon.

**Comment by iloveeclipse** [comment]
Do whatever you want if it makes things better.
